### ISSUE TITLE
清除浮动的方法

### ISSUE THREAD

**Issue by songning0605** [songning0605/blog#15]
- 伪类 `::after`
```css
zoom: 1;
&::before,
&::after {
    display: table;  // 设置为block也可以，这里主要是为了形成BFC，防止margin合并
    content: ' ';
}
&::after {
    clear: both;
    height: 0;
    font-size: 0;
    visibility: hidden;
}
```

- 父元素设置BFC #12 
```
display: table, inline-block;
overflow: hidden | auto | scroll;
```
