### ISSUE TITLE
使用Flex实现高度自适应三栏布局

### ISSUE THREAD

**Issue by songning0605** [songning0605/blog#4]
html代码如下
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>JS Bin</title>
</head>
<body>
  <div class="container">
    <header class="header">header</header>
    
    <main class="content">
      <div>test</div>
    </main>
    
    <footer class="footer">header</footer>
    </div>
  </div>
</body>
</html>
```
css代码如下
```css
html, body {
  height: 100%;
  margin: 0;
  padding: 0;
}
.container{
  display: flex;
  height: 100%;
  flex-direction: column;
}

.header{
  background: blue;
  flex: 0 0 60px;
}
.content{
  background: skyblue;
  flex: 1 1 auto;
  overflow: auto;
}
.test{
  height: 100vh;
}
.footer{
  background: blue;
  flex: 0 0 60px;
}
```

最终效果
![image](https://user-images.githubusercontent.com/31798032/82849292-c709b880-9f29-11ea-8a54-861ed9ff8aa1.png)
